# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pages.github.com/ml_tips/"

git_url = "n"

def custom_doc_links(name): return None
